homekit:
  pin: 58331770
controllers:
  - period: 115
    margin: 10
    min: 1
    max: 6
    next: 2
    down: 3
    hold: 4
    up: 17
  - period: 115
    margin: 10
    min: 1
    max: 6
    next: 27
    down: 22
    hold: 10
    up: 11
devices:
  - name: UG_RAUM_0
    controller: 0
    position: 1
  - name: EG_BIB
    controller: 0
    position: 2
  - name: EG_TUERE
    controller: 0
    position: 3
  - name: EG_WOHNZIMMER
    controller: 0
    position: 4
  - name: OG_RAUM_0
    controller: 0
    position 5
  - name: EG_ESSZIMMER
    controller: 1
    position: 1
