homekit:
  pin: 58331770
controllers:
  - period: 115
    margin: 10
    min: 1
    max: 6
    next: 2
    down: 3
    hold: 4
    up: 17
  - period: 115
    margin: 10
    min: 1
    max: 6
    next: 27
    down: 22
    hold: 10
    up: 11
devices:
  - name: Device_1
    controller: 0
    position: 1
  - name: Device_2
    controller: 1
    position: 1